### PR TITLE
Fixed a lot of things, and made var rename better.

### PR DESCRIPTION
**Pull request by Mp3Alt**

### CODE REVIEW

**Review by Serpensin — COMMENTED** [review]
What exactly is this? You didn't change anything substantial.
The only thing you did, is renaming some function in string_encoder, that doesn't change a thing. If you want the function names to be different, maybe put them through the random renamer for each time this module gets used instead of just putting `abcd` in front of them.

**Comment by playvoras** [comment]
the fck?

**Comment by Serpensin** [comment]
Yeah. This pretty much looks like an attempt to get in the contributor list, just for a pissing contest.

**Review by zeusssz — COMMENTED** [review]
yeah no what is this? you barely changed anything, and just added comments, `abcd` before names, etc. what does this pr even do.

**Comment by Serpensin** [comment]
Same thing here @zeusssz. Can we just close this PR?

**Comment by zeusssz** [comment]
> Same thing here @zeusssz. Can we just close this PR?

yep. will do. the justification here was that the variables in the code would interfere with some possible variables.
image
<br>
which is why he renamed the variables to this.
```lua
local decode_function = [[
local function ]] .. random_isvalidchar_name .. [[(abcdefbyte)
    return (abcdefbyte >= 48 and abcdefbyte <= 57) or (abcdefbyte >= 65 and abcdefbyte <= 90) or (abcdefbyte >= 97 and abcdefbyte <= 122)
end
    
local function ]] .. random_decrypt_name .. [[(code, offset)
    local abcderesult = {}
    for i = 1, #code do
        local abcdefbyte2 = code:byte(i)
        if ]] .. random_isvalidchar_name .. [[(abcdefbyte2) then
            local new_byte234
            if abcdefbyte2 >= 48 and abcdefbyte2 <= 57 then
                new_byte234 = ((abcdefbyte2 - 48 - offset + 10) % 10) + 48
            elseif abcdefbyte2 >= 65 and abcdefbyte2 <= 90 then
                new_byte234 = ((abcdefbyte2 - 65 - offset + 26) % 26) + 65
            elseif abcdefbyte2 >= 97 and abcdefbyte2 <= 122 then
                new_byte234 = ((abcdefbyte2 - 97 - offset + 26) % 26) + 97
            end
            table.insert(abcderesult, string.char(new_byte234))
        else
            table.insert(abcderesult, string.char(abcdefbyte2))
        end
    end
    return table.concat(abcderesult)
end
]]```

**Pull request closed without merging**
