### PR TITLE
Added test.py

### PR DESCRIPTION
**Pull request by Serpensin**
Added test.py, that tests all combination of modules, if they are working together. To test the combinations, a simple factorial calculation is executed.
```
function factorial(n)
    if n == 0 then
        return 1
    else
        return n * factorial(n - 1)
    end
end

local result = factorial(13)
print(result)
```

After the execution, you'll find a txt file, that contains the result for each test (successful/timeout/fail).
The result wont be the same on a re-run ofc, because the modules use randomized characters.

### CODE REVIEW

**Comment by Serpensin** [comment]
The number of tests is 2^9=512, since every possible combination is tested.

**Review by zeusssz — COMMENTED** [review]
@xthrx0 please do review these changes, as well as run tests.

**Review by xthrx0 — CHANGES_REQUESTED** [review]
reviewed changes. i request usage of parallel processes, to improve speed of the code. rough example below
```py
from concurrent.futures import ProcessPoolExecutor, as_completed

def run_pipeline(modified_pipeline):
    with open('./pipeline.lua', 'w') as f:
        f.write(modified_pipeline)

    try:
        subprocess.run([LUA, './hercules.lua', './testfile.lua'], check=True)
        result = subprocess.run([LUA, './testfile_obfuscated.lua'], capture_output=True, text=True, timeout=5)
        return '6227020800' in result.stdout, False
    except subprocess.TimeoutExpired:
        return False, True 

def test_combination(combination, original_pipeline_content):
    modified_pipeline = modify_pipeline(original_pipeline_content, combination)
    return combination, run_pipeline(modified_pipeline)

def main():
    # ...

    # prep combinations
    combinations = [combination for i in range(1, len(MODULES) + 1)
                    for combination in itertools.combinations([module[0] for module in MODULES], i)]

    # use 'ProcessPoolExecutor' for parallel execution
    with ProcessPoolExecutor() as executor:
        future_to_combination = {executor.submit(test_combination, comb, original_pipeline_content): comb for comb in combinations}
        
        for future in as_completed(future_to_combination):
            combination, (test_passed, test_timeout) = future.result()
            result = "[SUCCESS]" if test_passed else "[TIMEOUT]" if test_timeout else "[FAIL]"
            results.append(f"{result} ---- {', '.join(combination)}")
            total_tests += 1
            if test_passed:
                passed_tests += 1
            elif test_timeout:
                timeout_tests += 1

    # ...
```

**Comment by Serpensin** [comment]
That's not a thing, you can easily do, since each combination/run needs a different pipeline file. That's the reason, you can only do one task at a time.

**Comment by zeusssz** [comment]
512 tests will take a significant amount of computational power. jos is correct, we need some amount of optimization.

**Comment by Serpensin** [comment]
Multiprocessing will take even more power. And as I said, this can't be added, until you add the ability to change the pipeline filename. For example: `--pipeline pipeline123.lua`.

**Comment by zeusssz** [comment]
sorry, i meant time. not power. multiproc will take more resources, but lesser time. and instead of changing the pipeline file, you may directly edit it to run the tests.
adding a `--pipeline` flag is a good idea however, and we will look into implementing that

**Comment by Serpensin** [comment]
As soo as we have that flag available, I can change it and benchmark the time. Currently it takes ~100 seconds for all tests on my machine.

**Comment by zeusssz** [comment]
alright, ill add that flag in a bit

**Pull request closed without merging**
